site_name: Pembelajaran Mesin untuk Warna Artikel
site_url: https://colorskim.jpao.live/
nav:
  - Mengenai Pembelajaran Mesin: index.md
  - Mengenai ColorSkim: colorskim_intro.md
  - Dokumentasi ColorSkim: colorskim_notebook.md
theme:
  name: material
  icon:
    logo: fontawesome/solid/robot
  favicon: images/favicon.png
  palette:
    scheme: slate
    primary: black
    accent: red
  language: id
  font:
    text: Nunito
    code: JetBrains Mono
  highlightjs: true
  hljs_languages:
    - python
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - content.code.annotate
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.magiclink:
      repo_url_shortener: true
      provider: 'github'
      user: 'johanesPao'
      repo: 'ColorSkim'
  - tables
  - pymdownx.highlight:
      use_pygments: true
      linenums: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
extra_javascript:
  - javascripts/mathjax.js
  - javascripts/feedback.js
  - javascripts/consent.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/teh_kotak_lemon/
      name: jPao on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/johanesPao/
      name: jPao on GitHub
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/j0hanespao
      name: jPao on Docker
  version:
    provider: mike
  analytics:
    provider: google
    property: G-Q50VJ71SC8
    feedback:
      title: Apakah halaman ini bermanfaat?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Halaman ini bermanfaat
          data: 1
          note: >-
            Terima kasih atas feedbacknya!
        - icon: material/emoticon-sad-outline
          name: Halaman ini masih dapat diperbaiki
          data: 0
          note: >-
            Terima kasih atas feedbacknya! Bantu kami dalam memperbaiki 
            halaman ini menggunakan <a href="https://github.com/johanesPao/ColorSkim/issues/new/?title=[Feedback]+{title}+-+{url}" target=_blank>formulir feedback</a>
  consent:
    title: Persetujuan Penggunaan Cookies
    description: >-
      Halaman ini menggunakan cookies untuk mengenali kunjungan berulang dan preferensi pengunjung, juga untuk 
      mengukur keefektifan dari dokumentasi pada situs ini, serta untuk mengetahui apakah pengguna dapat menemukan 
      apa yang mereka cari. Dengan persetujuan anda, anda telah membantu kami dalam membuat dokumentasi yang lebih 
      baik
    cookies:
      analytics: Google Analytics
      custom: ColorSkim Cookies
    actions:
      - accept
      - manage
repo_url: https://github.com/johanesPao/ColorSkim
repo_name: johanesPao/ColorSkim
plugins:
  - tags
copyright: >
  Copyright &copy; 2022 - Johanes Indra Pradana Pao - 
  <a href="#__consent">Kelola pengaturan cookies</a>